/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PartyMasterRecord {
  'address' : string,
  'panNumber' : string,
  'partyName' : string,
  'phoneNumber' : string,
  'dueAmount' : bigint,
}
export interface PartyPaymentEntry {
  'entryLocation' : string,
  'date' : string,
  'address' : string,
  'panNumber' : string,
  'partyName' : string,
  'comments' : string,
  'phoneNumber' : string,
  'nextPaymentDate' : string,
  'payment' : bigint,
  'dueAmount' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createEntry' : ActorMethod<[string, PartyPaymentEntry], undefined>,
  'deleteEntry' : ActorMethod<[string], undefined>,
  'getAllEntries' : ActorMethod<[], Array<PartyPaymentEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEntry' : ActorMethod<[string], [] | [PartyPaymentEntry]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'lookupPartyMaster' : ActorMethod<[string], [] | [PartyMasterRecord]>,
  'registerUser' : ActorMethod<[], undefined>,
  'revokeUser' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateEntry' : ActorMethod<[string, PartyPaymentEntry], undefined>,
  'updatePartyMasters' : ActorMethod<
    [Array<[string, PartyMasterRecord]>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];