/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PartyPaymentEntry = IDL.Record({
  'totalWithTip' : IDL.Int,
  'entryLocation' : IDL.Text,
  'tipAmount' : IDL.Int,
  'totalCost' : IDL.Int,
  'description' : IDL.Text,
  'numPeople' : IDL.Int,
  'costPerPerson' : IDL.Int,
  'tipPercent' : IDL.Int,
});
export const PartyMasterRecord = IDL.Record({
  'address' : IDL.Text,
  'panNumber' : IDL.Text,
  'partyName' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'dueAmount' : IDL.Int,
});

export const idlService = IDL.Service({
  'createEntry' : IDL.Func([IDL.Text, PartyPaymentEntry], [], []),
  'getAllEntries' : IDL.Func([], [IDL.Vec(PartyPaymentEntry)], ['query']),
  'importPartyMasters' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, PartyMasterRecord))],
      [],
      [],
    ),
  'lookupPartyMaster' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PartyMasterRecord)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PartyPaymentEntry = IDL.Record({
    'totalWithTip' : IDL.Int,
    'entryLocation' : IDL.Text,
    'tipAmount' : IDL.Int,
    'totalCost' : IDL.Int,
    'description' : IDL.Text,
    'numPeople' : IDL.Int,
    'costPerPerson' : IDL.Int,
    'tipPercent' : IDL.Int,
  });
  const PartyMasterRecord = IDL.Record({
    'address' : IDL.Text,
    'panNumber' : IDL.Text,
    'partyName' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'dueAmount' : IDL.Int,
  });
  
  return IDL.Service({
    'createEntry' : IDL.Func([IDL.Text, PartyPaymentEntry], [], []),
    'getAllEntries' : IDL.Func([], [IDL.Vec(PartyPaymentEntry)], ['query']),
    'importPartyMasters' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, PartyMasterRecord))],
        [],
        [],
      ),
    'lookupPartyMaster' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PartyMasterRecord)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };