/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PartyMasterRecord {
  'address' : string,
  'panNumber' : string,
  'partyName' : string,
  'phoneNumber' : string,
  'dueAmount' : bigint,
}
export interface PartyPaymentEntry {
  'totalWithTip' : bigint,
  'entryLocation' : string,
  'tipAmount' : bigint,
  'totalCost' : bigint,
  'description' : string,
  'numPeople' : bigint,
  'costPerPerson' : bigint,
  'tipPercent' : bigint,
}
export interface _SERVICE {
  'createEntry' : ActorMethod<[string, PartyPaymentEntry], undefined>,
  'getAllEntries' : ActorMethod<[], Array<PartyPaymentEntry>>,
  'importPartyMasters' : ActorMethod<
    [Array<[string, PartyMasterRecord]>],
    undefined
  >,
  'lookupPartyMaster' : ActorMethod<[string], [] | [PartyMasterRecord]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];